### ISSUE TITLE
Pls add option to move brightness slider at the bottom (just like aosp mods)

### ISSUE THREAD

**Issue by parasgargexx20** [Mahmud0808/Iconify#327] opened 2023-10-27 13:35 UTC
### Describe the feature

The ability to move positioning of brightness slider to bottom (like give an option)

Example below - of what I mean by changing positioning of brightness slider 

![Screenshot_20231027-185009_Telegram X](https://github.com/Mahmud0808/Iconify/assets/102552831/c1c5d56c-573e-48b3-b82f-885fce76e9ec)

### Why would it be useful to add?

For better reachability on larger displays. (Since, roms like pixel experience and lineage os and pixel os and pixys don't have yet) (so people with this ability in Iconfiy app can use that feature on those very stable roms and wouldn't need to switch out to more heavy roms like evo x, elixir etc

### Example(s)

![Screenshot_20231027-185009_Telegram X](https://github.com/Mahmud0808/Iconify/assets/102552831/94c147f2-9301-4bd0-ad1d-3784397b7150)

![Screenshot_20231027-185006_Telegram X](https://github.com/Mahmud0808/Iconify/assets/102552831/a7098ea4-8a2e-4081-8d83-9c73ef8be03f)

### Additional context

Nope

**Comment by Mahmud0808** [comment] 2023-10-27 14:31
Duplicate of #217

**Closed as not planned by Mahmud0808** 2023-10-27 14:31 UTC
Labels: enhancement, feature
