### ISSUE TITLE
Visible volume percentage/steps

### ISSUE THREAD

**Issue by YOEL-44** [Mahmud0808/Iconify#477] opened 2024-04-08 03:06 UTC
### Describe the feature

I just want to be able to see the volume steps or percentage for each slider.
Many ROMs already include that as a feature (specially older ones, example is from RROS 8.7.3 A10) but it seems to be a deprecated feature in favor of a cleaner design, I guess.

### Why would it be useful to add?

Being able to quickly see the volume at which something is going to start to play, before doing so, is quite useful.

### Example(s)

![IMG_20240408_050013_684](https://github.com/Mahmud0808/Iconify/assets/7842997/d9a24f3e-c643-4c22-8446-64bc2bf23101)

### Additional context

I don't really mind how this is implemented design wise, I just want the number somewhere in or around the volume bar.

**Comment by HiFIi** [comment] 2024-04-08 03:36
🤔

**Comment by tomaszk8266** [comment] 2024-04-14 06:18
Duplicate of #114 ?

**Comment by YOEL-44** [comment] 2024-04-14 16:30
> Duplicate of #114 ?

I mean, as long as we can see that number, I wouldn't mind having that specific style.

**Closed as completed** 2024-04-16 18:50 UTC
Labels: enhancement, feature
