### ISSUE TITLE
[BUG] SystemUI crashed with iconify

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [Mahmud0808/Iconify#405] opened 2024-01-20 07:23 UTC
### Describe the bug

after change it my phone's SystemUI seems cannot work and myphone is auto-restart, then i found my phone only can display a gray screen and use Poweroff button

### Steps to reproduce

1. Go to 'Iconify APP'
2. Click on 'Modify the notification bar'
3. Scroll down to 'Choose Cyberpunk style'
4. Use it and See error

### Expected behavior

my phone should work normal

### Screenshots

nope, because  I cannot enter in SystemUI

### Device information

- Device: [RedmiNote9Pro 5G gauguin]
- OS: [PixelOS 02 January 2024]
- App version: [v 6.6.0]
- Magisk/KernelSU: [Magisk v26.4]

### Additional context

i want to fix my phone lol*

**Comment by Mahmud0808** [comment] 2024-01-20 07:27
Duplicate of #278

It's not notification styles, it's QS tile styles.

**Closed as not planned by Mahmud0808** 2024-01-20 07:27 UTC
Labels: bug

**Comment by HiFIi** [comment] 2024-01-22 05:48
This project is dead

**Comment by adeptmicors279** [comment] 2025-06-06 15:29
请问找到解决方案了吗，我也遇到了这个问题
Pls did you find a solution, I'm also experiencing this issue
