### ISSUE TITLE
[FEATURE] Rounded QS tiles or even better shaped mask options if possible

### ISSUE THREAD

**Issue by jeanrivera** [Mahmud0808/Iconify#626] opened 2024-09-21 03:16 UTC
### Describe the feature

have the ability to have QS tiles rounded (perfect circle) or desired shape with masked shapes like launcher icons options

### Why would it be useful to add?

it is an excellent customization option, and it would be a great addition to this fantastic customization tool

### Example(s)

![main-qimg-eb92eaabdcd3a7633bba9c1703cbf88a-pjlq](https://github.com/user-attachments/assets/e880d281-8435-4109-9550-326c03d502e3)

![my-quick-settings-panel-keeps-re-shuffling-every-time-i-v0-r5mj5gtirtvc1](https://github.com/user-attachments/assets/adea48e9-3aa8-4bb2-94e3-7ad9daa878a9)

![android-q-quick-settings-toggles](https://github.com/user-attachments/assets/753b500d-de66-4d5c-a8f2-feeb96491f34)

**Comment by Mahmud0808** [comment] 2024-09-21 03:42
Duplicate of #243

**Closed as not planned by Mahmud0808** 2024-09-21 03:42 UTC
Labels: enhancement, feature
