### ISSUE TITLE
[BUG] always crashing during install while generating overlay apks

### ISSUE THREAD

**Issue by exolon** [Mahmud0808/Iconify#422] opened 2024-02-02 13:34 UTC
### Describe the bug

Upon installation when the step when the overlay apks are generated it crashes. Uninstalling and trying again didn't work. 

6.7.0 under 14 (AP11.231215.009)

### Steps to reproduce

1. Run app 

### Expected behavior

Generate the apks and continue

### Device information

Pixel 7 Pro 
14 (AP11.231215.009)
Magiskalpha -26405
6.7.0

**Comment by Mahmud0808** [comment] 2024-02-02 13:55
Duplicate of #366

**Closed as not planned by Mahmud0808** 2024-02-02 13:55 UTC
Labels: bug
