### ISSUE TITLE
[BUG] Getting an Initial Setup Error

### ISSUE THREAD

**Issue by princawa** [Mahmud0808/Iconify#392] opened 2023-12-29 07:18 UTC
### Describe the bug

When I tried to start the app up, I got a message that said, "Oops, Did Not Expect That... Logs have been saved in documents folder. Attached is the logcat.
[iconify_logcat_28-12-23_23_08_00.txt](https://github.com/Mahmud0808/Iconify/files/13791600/iconify_logcat_28-12-23_23_08_00.txt)
"

### Expected behavior

I expected the Iconify app to finish setting up properly since I have a rooted Pixel 7 Pro running Android 14.

### Screenshots

![Screenshot_20231228-231727](https://github.com/Mahmud0808/Iconify/assets/36582247/371b330d-d227-4042-aedc-73985d1e36b2)

### Device information

- Device: Google Pixel 7 Pro
- OS: Stock Android 14 Build: AP11.23117.006
- App version: 6.6.0
- Magisk/KernelSU: Magisk Canary 26.4

**Comment by HiFIi** [comment] 2023-12-29 14:03
Known issue, iconify is mostly dead for the most part as it's a giant giant task having to change the code. This is directly from the devs mouth. ColorBlendr is the new project

**Comment by Mahmud0808** [comment] 2023-12-29 19:45
Duplicate of #366

**Closed as not planned by Mahmud0808** 2023-12-29 19:45 UTC
Labels: bug, duplicate
