### ISSUE TITLE
[BUG] Iconify QS tile shape mod causing system crash

### ISSUE THREAD

**Issue by UberNorse** [Mahmud0808/Iconify#369] opened 2023-12-06 18:23 UTC
### Describe the bug

Hello,
Upon updating to QPR1 on the Pixel 7 Pro today I have found out that trying to modify QS tile type causes immediate system crash with a reboot to recovery stating that system can't boot and data is corrupt. I have since reinstalled Iconify on new QPR1 and enabled most other modifications I had with no issue. Hope this helps. 

### Steps to reproduce

1.  Update to Android 14 Stable 05-12 QPR1
2.  Use Iconify to modify QS tile shape
3.  System crash with auto reboot to recovery stating data is corrupt and system can't boot. 

### Expected behavior

Did not expect it to crash but only modify QS tile shape. 

### Device information

- Device: [Pixel 7 Pro]
- OS: [Stock ROM Android Stable 14 QPR1]
- App version: [V6.6.0]
- Magisk/KernelSU: [Magisk 26400 and 26402]

**Comment by craigacgomez** [comment] 2023-12-07 19:20
This is already mentioned in other open tickets
https://github.com/Mahmud0808/Iconify/issues/313
https://github.com/Mahmud0808/Iconify/issues/278

**Comment by Mahmud0808** [comment] 2023-12-07 19:37
Duplicate of #278

**Closed as not planned by Mahmud0808** 2023-12-07 19:37 UTC
Labels: bug, duplicate
