### ISSUE TITLE
Screen goes black when theming any QS 

### ISSUE THREAD

**Issue by bradhoschar** [Mahmud0808/Iconify#384] opened 2023-12-16 03:41 UTC
### Describe the bug

Pixel 7 Pro. Iconify 6.6.0.
When trying to theme any quick setting tile, and restarting system UI, screen just goes black and non-responsive. No other theming setting makes my phone crash like this. 
Have to restart in safe mode, then enter repair mode, then restart phone normally, and re-enable magisk modules.
Don't think it did it on the previous version. 
![Screenshot_20231215-222831](https://github.com/Mahmud0808/Iconify/assets/1077385/11cc7fc7-e864-418f-935a-1d409d303762)

### Expected behavior

Quick settings panel to be themed correctly

### Device information

- Device: Pixel 7 pro
- OS: A14 December build
- App version: 6.6.0
- Magisk/KernelSU: Canary, stock

**Comment by Mahmud0808** [comment] 2023-12-16 06:49
Duplicate of #278

**Closed as not planned** 2023-12-16 06:51 UTC
Labels: bug, duplicate

**Comment by bradhoschar** [comment] 2023-12-16 06:59
Looks like issue 278 is related to Android 14 QPR1 Beta 1.
I'm running Stable A14, build number UQ1A.231205.015.

**Comment by Mahmud0808** [comment] 2023-12-16 07:01
December build is basically QPR1. The issue is exactly same, crash log is also same. So it's a duplicate even though different rom. And no one is providing logs so I can't help further.

**Comment by bradhoschar** [comment] 2023-12-16 07:30
I'll get you logs tomorrow. 
Thanks for the quick reply
