### ISSUE TITLE
[BUG] Iconify causes bootloops on QPR 1 U1B2

### ISSUE THREAD

**Issue by ASPNyan** [Mahmud0808/Iconify#313] opened 2023-10-15 13:42 UTC
### Describe the bug

Applying modifications in Iconify or having the `Iconify Companion` Magisk module installed cause bootloops with the error: `Cannot load Android System` ([this](https://storage.googleapis.com/support-forums-api/attachment/thread-185178025-4009211010012833086.jpg) is the same error, but a different device). This started since I updated to QPR 1's U1B2 update (latest as of Oct. 15), and seems to happen on both Pixel 6 and 7 boots.

### Steps to reproduce

1. Update to latest Android version (currently U1B2.230922.006); Pixel images can be found [here](https://developer.android.com/about/versions/14/download).
2. Install Magisk (duh), and install Iconify (duh, the sequel).
3. If at this stage you also want to try the Companion module, install that now.
4. Restart
5. If you installed the companion module, expect a weird boot sequence followed by a failed boot, a restart, and a display then showing the [aforementioned error](https://storage.googleapis.com/support-forums-api/attachment/thread-185178025-4009211010012833086.jpg). If you don't install the companion, try applying a setting. You should then have a System UI restart, followed by a System UI (or at least I assume to be) crash, causing a restart, and then following the same sequence as the Companion module.

### Expected behavior

Not to bootloop? Just to apply the settings like normal.

### Screenshots

Well no screenshots, but there is the previous photos of the error so here's the raw link: https://storage.googleapis.com/support-forums-api/attachment/thread-185178025-4009211010012833086.jpg

### Device information

- Device: Pixel 6
- OS: Stock Pixel 6 (and 7) ROM(s), Android 14 U1B2
- App version: 6.5.1

### Additional context

From my limited analysis, since the device restarts pretty quickly after the first boot (before the failure to load boot error message), it seems that System UI is removed from the device. This could indicate some misbehavior with System UI and the module. Additionally, since the module fails instantly and the base app only on apply, there could be correlation? I only tried the base app once, and I did import my settings so if there's a correlation between what the companion does and my settings, [here's the file](https://drive.google.com/file/d/178xaS-cMtIaGS_UXG2Xn9Ux9Ix6D6dIK/view?usp=drivesdk) for it (just in case). Unfortunately I don't know a thing about Java and Kotlin, and especially not for root, so I can't help by looking through code. But if you need more info, let me know.

**Comment by Mahmud0808** [comment] 2023-10-15 13:48
Thank you for the detailed report. The bootloop issue on A14 QPR builds is already known. It happens when you enable any QS Tile Styles. Other customizations should work fine. Can't really fix without getting the source code which is still far away.

Didn't know about the companion module also causing issue, I'll investigate.

**Comment by 5thofjuly** [comment] 2023-10-17 19:03
> Thank you for the detailed report. The bootloop issue on A14 QPR builds is already known. It happens when you enable any QS Tile Styles. Other customizations should work fine. Can't really fix without getting the source code which is still far away.
> 
> Didn't know about the companion module also causing issue, I'll investigate.

May I ask if the Transparency and Blur mod also trigger the issie?

**Comment by Mahmud0808** [comment] 2023-10-24 15:56
> May I ask if the Transparency and Blur mod also trigger the issie?

No, these should work fine. Atleast in my testing, there wasn't any issue.

**Comment by Mahmud0808** [comment] 2023-12-07 19:37
Duplicate of #278

**Closed as not planned by Mahmud0808** 2023-12-07 19:37 UTC
Labels: bug
