### ISSUE TITLE
[FEATURE] Recent Items/Apps customization

### ISSUE THREAD

**Issue by ghost** [Mahmud0808/Iconify#322] opened 2023-10-20 10:26 UTC
### Describe the feature

Giving us an option to customize the recent apps. Like customizing titles or whatever you calls it.

### Why would it be useful to add?

Would actually make our Android phone looks a lot better.

### Example(s)

![Screenshot_20231020-181858_Iconify~2](https://github.com/Mahmud0808/Iconify/assets/106787899/d9ff2b90-d40e-4fd5-8b2c-0a46062d9891)

# **PLEASE ADD TRANSPARENT OPINIONS TO IT!**

### Additional context

# **PLEASE ADD TRANSPARENT OPINIONS TO IT!**

**Comment by tadekdudek** [comment] 2023-10-20 10:29
Recents menu is a part of launcher, so it is ROM-depended. Customizing them will probably cause instability.

**Comment by tadekdudek** [comment] 2023-10-20 10:31
Duplicate of #196?

**Comment by ghost** [comment] 2023-10-20 10:35
> Duplicate of #196?

Probably not. What I am thinking is it would be great if you can customize the buttons position and maybe adding maybe outlines and background to the buttons.
~English wasn't my primary language, sry for bad english~

**Comment by ghost** [comment] 2023-10-20 10:38
> Recents menu is a part of launcher, so it is ROM-depended. Customizing them will probably cause instability.

I personality think that there aren't any significantly visible of the recent items. At least no one has really mentioned any custom rom did any significantly visible/cool modification to it. The chance of instability might be lower then expectation.

**Comment by Mahmud0808** [comment] 2023-10-24 18:34
Your feature request isn't clear.

Edit: No further response. Hence closing.

**Closed as not planned** 2023-11-28 18:32 UTC
Labels: enhancement, question, wontfix, feature
