### ISSUE TITLE
[FEATURE] Android 11 Style qs panel

### ISSUE THREAD

**Issue by Samarth170102** [Mahmud0808/Iconify#628] opened 2024-09-21 15:29 UTC
### Describe the feature

Basically a feature which turn qs panel to android 11 style qs panel.

### Why would it be useful to add?

As a user which use Crdroid 9.8 which is based on Android 13, It doesn't have feature to turn qs panel to android 11 style, so this feature may be useful for people who do not want to update to latest version of rom but wants the features.

### Example(s)

![images](https://github.com/user-attachments/assets/e1bcdab3-58da-443e-85aa-557594265787)

**Comment by Mahmud0808** [comment] 2024-09-21 15:34
Duplicate of #243

**Closed as not planned by Mahmud0808** 2024-09-21 15:34 UTC
Labels: enhancement, feature
