### ISSUE TITLE
[FEATURE] Remove lock icon in the lock screen 

### ISSUE THREAD

**Issue by AndyKaslana** [Mahmud0808/Iconify#351] opened 2023-11-14 15:22 UTC
### Describe the feature

Remove the lock icon located in the lower part of the lock screen

### Why would it be useful to add?

Avoid ugly overlapping with the notifications and media controls when these are in the lower part of the screen. Plus, the lock icon it's useless and removing it would let the user with a more cleaner and esthetically pleasing lock screen.

### Example(s)

![Screenshot_20231114-101654_Iconify](https://github.com/Mahmud0808/Iconify/assets/150069135/2f3c76c6-4e43-4302-adf8-8f79b812c4fb)

![Screenshot_20231114-101530_Pixel Launcher](https://github.com/Mahmud0808/Iconify/assets/150069135/69630398-619a-42f9-9c7d-15e71349df47)

**Comment by Mahmud0808** [comment] 2023-11-28 18:38
Duplicate of #251

**Closed as not planned by Mahmud0808** 2023-11-28 18:38 UTC
Labels: duplicate, enhancement, feature
