### ISSUE TITLE
[BUG] Theming Quick Tiles crashes SystemUI without bringing it back on A14 231205

### ISSUE THREAD

**Issue by cozykitten** [Mahmud0808/Iconify#375] opened 2023-12-10 18:23 UTC
### Describe the bug

- updated my phone to December OTA
- imported my iconify config from before the update
- screen goes black, "SystemUI not responding" dialogue appears, it doesn't restart, I reboot, and after boot completes the screen stays blank
- I disabled the Iconify module through Pixelflasher and rebooted and it was back
- I tried manually applying my settings, Brightness bar worked, when I applies Quick Tiles theming the same thing happened again

### Steps to reproduce

pretty much listed above

### Expected behavior

normally settings sort of apply with a few things that don't fully apply directly, such as black text on quick tiles instead of white, but after a reboot all works.

### Device information

- Device: Pixel 6a
- OS: [e.g. A14 231205 (December OTA)
- App version: 6.6.0
- Magisk/KernelSU: Magisk 26.4

**Comment by Mahmud0808** [comment] 2023-12-10 18:26
Duplicate of #278

Already checked source code and still couldn't figure out what's the issue. Will wait for a rom to be available for my device.

**Closed as not planned by Mahmud0808** 2023-12-10 18:26 UTC
Labels: bug, duplicate

**Comment by cozykitten** [comment] 2023-12-10 18:30
Is there a way to edit the iconify config so that I can just remove the quick tiles option and import the rest?
or maybe a way to import the config in iconify but not immediately apply the new settings?

**Comment by Mahmud0808** [comment] 2023-12-10 18:56
> Is there a way to edit the iconify config so that I can just remove the quick tiles option and import the rest? or maybe a way to import the config in iconify but not immediately apply the new settings?

I don't think you can do that. Although there is one tricky way. Go to `data/adb/modules/Iconify/system/product/overlay/` delete (keep backup if you want) all APKs named IconifyComponentQSSN* and IconifyComponentQSSP* after that reboot and import your configs.

**Comment by cozykitten** [comment] 2023-12-10 18:59
That way it will not go into LSPosed only mode and instead apply the config, but all the overlay stuff simply won't be able to apply, resulting in my settings showing in the app, being changable and re-exportable?

**Comment by Mahmud0808** [comment] 2023-12-18 07:12
If you did what I said, it should be fine.
