### ISSUE TITLE
(BUG) Missing Settings icon

### ISSUE THREAD

**Issue by allday5850** [Mahmud0808/Iconify#521] opened 2024-06-10 07:39 UTC
### Describe the bug

Missing themed icon in settings. There are actually 2 missing, but one of them isn't really your problem because it wasn't created by Android. But still adding it just in case you can work your magic. 
1. ic_logo_google.xml
![Screenshot_20240610-033007](https://github.com/Mahmud0808/Iconify/assets/51069235/7aed6096-3212-4504-9c92-3ef6e9444012)
2. Pixel Expert (which isn't possible or isn't worth the trouble)

### Steps to reproduce

N/A

### Expected behavior

N/A

### Device information

- Device: Pixel 6
- OS: Stock Android 14 QPR1
- App version: 6.8.0dev
- Magisk/KernelSU: Magisk 27

**Comment by Mahmud0808** [comment] 2024-06-10 07:42
Are you sure it's ic_logo_google.xml ? Because this icon should be from digital wellbeing app and not settings app. (or I might be wrong)

**Comment by allday5850** [comment] 2024-06-11 19:57
Well, when I use overlays from substratum, it's always under Google Play Services. There is separate one for Digital Wellbeing. Which I have disabled so that's why it's not in SC

**Comment by allday5850** [comment] 2024-06-11 19:58
But when activate overlay for Google Play Service, the "G" logo is themed so I'm assuming that's where it's at.. could I look into the Play Services app just like Settings APK and see?

**Comment by Mahmud0808** [comment] 2024-06-11 20:02
Package name com.google.android.gms? Check inside and let me know the icon name.

**Comment by Mahmud0808** [comment] 2024-08-14 19:49
duplicate of #417

**Closed as not planned by Mahmud0808** 2024-08-14 19:49 UTC
Labels: bug
