### ISSUE TITLE
[FEATURE] Transparent QS icons

### ISSUE THREAD

**Issue by eddieofny** [Mahmud0808/Iconify#683] opened 2024-11-22 06:15 UTC
### Describe the feature

If possible, I think it would be cool if transparent QS tiles were an option, maybe with the ability to highlight the icons themselves with the system accent color.

### Why would it be useful to add?

I would like this feature because I hate the new Android QS panel and I primarily use Iconify to make it look as much as possible like the old QS panel.

### Example(s)

N/a

**Comment by Mahmud0808** [comment] 2024-11-22 14:25
Duplicate of #382

**Closed as not planned by Mahmud0808** 2024-11-22 14:25 UTC
Labels: enhancement, feature
