### ISSUE TITLE
[BUG] Transparent QS Panel has black notches

### ISSUE THREAD

**Issue by ItsRogueRen** [Mahmud0808/Iconify#693] opened 2024-12-07 22:06 UTC
### Describe the bug

When using the Transparent QS Panel option, there are small black curves on either side of the top of the Notification shade. The look like they would function as a sort of drop shadow on the solid notification shade, but when made transparent they become unneeded and unappealing.

### Steps to reproduce

1. Go to 'Iconify'
2. Click on 'Xposed'
3. Click on 'Transparency & Blur'
4. Enabled 'Transparent QS Panel'
5. Go to a light colored screen, i.e. your home screen with a light background
6. Swipe down to open the QS Panel and see the black curves where the notifications start

### Expected behavior

Black notched to also be transparent and/or blurred

### Screenshots

![Screenshot_20241207-160222_1](https://github.com/user-attachments/assets/51bce657-1068-47a2-8eef-b74912216f9f)

### Device information

- Device: Moto G Stylus 5G 2023
- OS: Stock A14
- App version: 6.9.0
- Magisk/KernelSU: Magisk 27.0

**Comment by Mahmud0808** [comment] 2024-12-08 07:04
Duplicate of #642

**Closed as not planned by Mahmud0808** 2024-12-08 07:04 UTC
Labels: bug
