### ISSUE TITLE
blur looks weird with values over 50

### ISSUE THREAD

**Issue by elisenlebkuch** [Mahmud0808/Iconify#308] opened 2023-10-14 15:10 UTC
### Describe the bug

https://github.com/Mahmud0808/Iconify/assets/127782512/f2e503ac-aa1e-4776-9d7f-e534df6dd0dd

### Steps to reproduce

1. Go to Igonify > Tweaks > Transparency & Blur.
2. Set Blur Intensity to a value bigger than 50(in this exapmle it was 152).

### Expected behavior

I expect it to look more like this:
![Screenshot_20231014-170939_Lawnchair](https://github.com/Mahmud0808/Iconify/assets/127782512/c356eddf-19cf-419c-a2d1-5c039db4a7b0)

### Device information

- Device: Fairphone FP3
- OS: DivestOS(newest available version)
- App version: newest non-development-version available

**Comment by tadekdudek** [comment] 2023-10-14 15:12
Duplicate of #197?

**Comment by elisenlebkuch** [comment] 2023-10-14 15:18
Sorry, I didn't see it yet.

**Closed as not planned** 2023-10-14 15:19 UTC
Labels: bug, wontfix

**Comment by elisenlebkuch** [comment] 2023-10-14 15:21
Could I do a feature request then?
